### ISSUE TITLE
trained model

### ISSUE THREAD

**Issue by mad-fogs** [Gbellport/QR-code-localization-YOLOv3#1]
Hi @Gbellport ,

nice work. will you release the trained model for qr code detection?

**Comment by Gbellport** [comment]
Thank you @mad-fogs. I will upload the weights and model sometime soon, I was planning on further training the model but haven’t found the time to revisit this project.

**Comment by bazinga007** [comment]
> Thank you @mad-fogs. I will upload the weights and model sometime soon, I was planning on further training the model but haven’t found the time to revisit this project.

Hey so I'm was also trying to achieve same thing for real time qr code detection in room environment as i tried mutliple configuration for training but accuracy doesn't seem to be really good if image is bit far like 4 feet from camera. My final loss was 0.059 for YoloV3- tiny. fps is around 30 fps with tiny.
![Screenshot (44)](https://user-images.githubusercontent.com/9152386/76600099-4a6f5c80-652c-11ea-9c71-f33345d49b26.png)
![Screenshot (45)](https://user-images.githubusercontent.com/9152386/76600109-4c392000-652c-11ea-929c-2459f437fb83.png)
![Screenshot (46)](https://user-images.githubusercontent.com/9152386/76600111-4d6a4d00-652c-11ea-890d-f9ed2350225e.png)
first Image if from like 1.5 Feet, 2nd 1 feet, 3rd 1.5 feet.
If you can share the configs i can train as i have PC for training at home that is left alone when i go for work.

**Comment by bazinga007** [comment]
> Hi @Gbellport ,
> 
> nice work. will you release the trained model for qr code detection?

hey can share some insight on what u trying to achieve so it would be better to collaborate with
each other for better results. Thanks

**Comment by bazinga007** [comment]
> Thank you @mad-fogs. I will upload the weights and model sometime soon, I was planning on further training the model but haven’t found the time to revisit this project.

I have data set of 115 Images for now with, for how many images u have trained your set?

**Comment by Gbellport** [comment]
Just uploaded the config files for the yolov3-tiny I used. The weights file is too big, so [here's](https://drive.google.com/open?id=1ArR0nrEPaEw_w1GHLeFoCDnAlbZpYERV) a link to the file on my drive in the meantime.

**Comment by Gbellport** [comment]
> > Thank you @mad-fogs. I will upload the weights and model sometime soon, I was planning on further training the model but haven’t found the time to revisit this project.
> 
> I have data set of 115 Images for now with, for how many images u have trained your set?

I trained on ~800 images which I manually labeled, making sure to get some variety on the quantity of QR codes on each image.

**Comment by bazinga007** [comment]
Thank you so much I 'll try it out. Also, I will create a dataset of 1000-1500 images for making the detection better. Creating a dataset is the most important part I guess. Maybe we will share dataset for more images once im ready with my dataset. 
Also i have one more question about which camera you are using for live detection and is it possible all the time to read the QR from the detected frame?

**Comment by bazinga007** [comment]
What was your Final loss?

**Comment by Gbellport** [comment]
I don't recall, it was a while ago. I am sure after gathering more images you'll have much better results. I used my laptop's camera (surface laptop 1), and also tested with videos I recorded on iphone X. I used OpenCV to read the QR codes, but I was unable to read small ones. I also tried using some opencv tricks to make the QR codes look less grainy but they got distorted.

**Comment by mad-fogs** [comment]
thanks very much for all's reply.
i have trained another model on private dataset, so will close this issue.
