### ISSUE TITLE
Model Weights

### ISSUE THREAD

**Issue by stark10war** [Gbellport/QR-code-localization-YOLOv3#2]
Hi Gabriel, Can you please add the trained weights file, .cfg and .names file so that I can use the trained model?? Thanks !

**Comment by Gbellport** [comment]
I believe the .cfg file is uploaded, but the weights were too big to upload. I have them in my Drive so here you go: https://drive.google.com/file/d/1ArR0nrEPaEw_w1GHLeFoCDnAlbZpYERV/view?usp=sharing
Good luck!

**Comment by mischamarty** [comment]
Hi Gabriel, Could you please add dataset files, so we could train yolov3 not tiny model? We can share our results afterward.

**Comment by Gbellport** [comment]
Hey,

The file's too big to add it on github, but here's a link to my project
folder on Drive with the data and bounding box annotations:
https://drive.google.com/drive/folders/1cAucDxkNCjeJ255H1vXY3DOPlVxwWwvC?usp=sharing

Good luck!
Gabriel

**Comment by akshayjaryal603** [comment]
Thanks @Gbellport you save my day! 
Happy Coding!

Best Regards
Akshay Jaryal
